# Generated by Django 5.1.4 on 2025-01-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_SERVICE', 'Out of Service'), ('OCCUPIED', 'Occupied'), ('NEEDS_CLEANING', 'Needs Cleaning'), ('DELETE', 'Delete')], default='AVAILABLE', max_length=20)),
                ('is_reserved', models.BooleanField(default=False)),
                ('reserved_time', models.DateTimeField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tables',
            },
        ),
    ]
