# Generated by Django 5.1.5 on 2025-01-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_SERVICE', 'Out of Service'), ('OCCUPIED', 'Occupied'), ('NEEDS_CLEANING', 'Needs Cleaning'), ('DELETE', 'Delete')], default='OUT_OF_SERVICE', max_length=20),
        ),
    ]
