server:
  port: 8080

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: 3600 #in seconds
  refreshable-duration: 360000 #in seconds

firebase:
  credentials: classpath:serviceAccountKey.json