# Generated by Django 4.2.18 on 2025-01-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0002_alter_menu_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
