# Generated by Django 5.1.5 on 2025-01-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
    ]
