server:
  port: 8888

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080/api/users
          predicates:
            - Path=/api/users/**