server:
  port: 8888

app:
  api-prefix: /savorgo/api

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/users/**
          filters:
            - StripPrefix=2
logging:
  include-application-name: