server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/savorgo
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: root
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
<<<<<<< Updated upstream
firebase:
  credentials: classpath:serviceAccountKey.json
=======
>>>>>>> Stashed changes
